name: weixin
on:
  workflow_dispatch:
  schedule: 
    # UTC时间23点 = 北京时间次日早上7点，按需自己改
    - cron: '0 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Set timezone
        run: |
          timedatectl set-timezone Asia/Shanghai
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip install requests zhdate
      - name: Run python script
        run: |
          python main.py
